### ISSUE TITLE
We should not need to call `.apply` on our `functional.finufft_type*` functions

### ISSUE THREAD

**Issue by eickenberg** [flatironinstitute/pytorch-finufft#84]
Need to look up how `torch.nn.functional` handles this.

I don't think it's `__call__=apply`, because this would be the `__call__` of the meta class, which is usually a call to the constructor ...

**Comment by WardBrian** [comment]
Based on the [`Extending Pytorch`](https://pytorch.org/docs/stable/notes/extending.html#extending-pytorch) docs, it seems like the recommended way to do this is to just define a new function which does what we want.

This seems nice because we could also then pass true kwargs. 
They give the example:

```python
class MyCube(torch.autograd.Function):
    # forward, backward omitted
    pass

# Wrap MyCube in a function so that it is clearer what the output is
def my_cube(x):
    result, dx = MyCube.apply(x)
    return result
```

So we could write 
```python
def finufft_type1(points, values,  output_shape, **finufftkwargs):
    return FinufftType1.apply(points, values, output_shape, finufftkwargs)
```
